- alias: 'Ocelotte Config Build Passed Announce '
  trigger:
  - entity_id: sensor.obscenediversion_ha_config_state
    from: started
    platform: state
    to: passed
  condition:
  - condition: state
    entity_id: person.rijk
    state: home
  action:
     service: tts.google_say
     data:
       entity_id: media_player.living_room_speaker
       message: Ocelotte configuration build passed.
