- alias: 'Ocelotte Config Build Failed Announce '
  trigger:
  - entity_id: sensor.obscenediversion_ha_config_state
    from: started
    platform: state
    to: failed
  condition:
  - condition: state
    entity_id: person.rijk
    state: home
  action:
    service: tts.google_say
    data:
     entity_id: media_player.living_room_speaker
     message: Ocelotte config build failed.
