- alias: 'Ocelotte Build Passed Notification'
  trigger:
  - entity_id: sensor.obscenediversion_ha_config_state
    from: started
    platform: state
    to: passed
  condition: []
  action:
    service: mqtt.publish
    data:
      topic: "homeassistant/tts/android_rijk_galaxy_s9_plus_tts/tts"
      payload: "Ocelotte configuration build passed!"
    service: notify.mobile_app_rijk_galaxy_s9_plus
    data:
      message: "Ocelotte cobfiguration build passed!"
