homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: -23
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_merge_named package/
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
frontend:
  themes: !include_dir_merge_named themes
  extra_html_url:
    - /local/custom_ui/state-card-floorplan.html
    
panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
   base_url: !secret baseurl
   ssl_certificate: !secret ssl_certificate
   ssl_key: !secret ssl_key
 
# Discover some devices automatically
discovery:
sun:
logger:

# Toon
toon:
  client_id: !secret toon_id
  client_secret: !secret toon_secret
  
# Spotify

media_player:
  - platform: spotify
    client_id: !secret spotify_clientid
    client_secret: !secret spotify_clientsecret

spotcast:
 username: !secret spotify_username
 password: !secret spotify_password
 
# HACS
 
hacs:
  token: !secret github_token_hacs
  
speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

group: !include_dir_merge_list group/
automation: !include_dir_merge_list automation/
#script: !include_dir_merge_named script/
script: !include scripts.yaml
zone:  !include_dir_merge_list zone/
sensor: !include_dir_merge_list sensor/
switch: !include_dir_merge_list switch/
tts: !include_dir_merge_list tts/
lock:  !include_dir_merge_list lock/
remote: !include_dir_merge_list remote/
binary_sensor: !include_dir_merge_list binary_sensor/