homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: -23
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_merge_named package/
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
   base_url: !secret baseurl
   ssl_certificate: !secret ssl_certificate
   ssl_key: !secret ssl_key
 
# Discover some devices automatically
discovery:

# Text to speech
#tts:
#  - platform: google_translate

# Toon
toon:
  client_id: !secret toon_id
  client_secret: !secret toon_secret

group: !include_dir_merge_list group/
automation: !include_dir_merge_list automation/
script: !include_dir_merge_list script/
zone:  !include_dir_merge_list zone/
sensor: !include_dir_merge_list sensor/
switch: !include_dir_merge_list switch/
#customize: !include_dir_merge_list customize/
tts: !include_dir_merge_list tts/