- alias: Travis CI Failed Notification
  trigger:
  - entity_id: sensor.obscenediversion_ha_config_state
    from: started
    platform: state
    to: failed
  condition: []
  action:
    service: mqtt.publish
    data:
      topic: "homeassistant/tts/android_rijk_galaxy_s9_plus_tts/tts"
      payload: "Ocelotte config build failed!"
- alias: Travis CI Passed Notification
  trigger:
  - entity_id: sensor.obscenediversion_ha_config_state
    from: started
    platform: state
    to: passed
  condition: []
  action:
    service: mqtt.publish
    data:
      topic: "homeassistant/tts/android_rijk_galaxy_s9_plus_tts/tts"
      payload: "Ocelotte config build passed!"
- alias: 'Travis build passed announce '
  trigger:
  - entity_id: sensor.obscenediversion_ha_config_state
    from: started
    platform: state
    to: passed
  condition:
  - condition: state
    entity_id: person.rijk
    state: home
  action:
     service: tts.google_say
     data:
       entity_id: media_player.living_room_speaker
       message: Ocelotte config build passed.
- alias: 'Travis build failed announce '
  trigger:
  - entity_id: sensor.obscenediversion_ha_config_state
    from: started
    platform: state
    to: failed
  condition:
  - condition: state
    entity_id: person.rijk
    state: home
  action:
    service: tts.google_say
    data:
     entity_id: media_player.living_room_speaker
     message: Ocelotte config build failed.
