- alias: Travis CI Failed Notification
  trigger:
  - entity_id: sensor.obscenediversion_ha_config_state
    from: started
    platform: state
    to: failes
  condition: []
  action:
    service: mqtt.publish
    data:
      topic: "homeassistant/tts/android_rijk_galaxy_s9_plus_tts/tts"
      payload: "Travis CI build failed!"

    
