- alias: Rijk Home.
  trigger:
  - entity_id: person.rijk
    platform: state
    to: 'Home'
  condition: []
  action:
  - data:
      entity_id: media_player.living_room_speaker
      message: Rijk is home.
    service: tts.google_say
    